### ISSUE TITLE
Details of Information Flow of TPN

### ISSUE THREAD

**Issue by dreamerlin** [decisionforce/TPN#17]
Thanks for your awesome work.
I found the code in [these lines](https://github.com/decisionforce/TPN/blob/master/mmaction/models/tenons/necks/tpn.py#L316-L333) are corresponding to the section 3.2 in the paper, which serves for fetching the information flow of TPN. I guess it is a `Parallel Flow` since in [L316](https://github.com/decisionforce/TPN/blob/master/mmaction/models/tenons/necks/tpn.py#L316) and [L325](https://github.com/decisionforce/TPN/blob/master/mmaction/models/tenons/necks/tpn.py#L325) the `out` is Intentionally assigned with `temporal_modulation_outs`. However, since `=` is a shadow copy, the `temporal_modulation_outs` changes before the second `=`, and it should be equal to out, resulting in a `Cascade Flow`.
Could you help me figure it out which the flow it should be ?

**Comment by limbo0000** [comment]
Hi @dreamerlin ,
The shadow copy indeed leads to the cascade flow instead of parallel one. In order to release code, we cleaned up and re-organized the original codebase and made the minor change on TPN (\eg hyperparameters of arch). It occurred in the re-organizing process. The released weights were also retrained on the current codebase. We will retrain the model of the parallel one. Thanks for pointing out such issue.

**Comment by limbo0000** [comment]
Hi @dreamerlin ,
We have retrained the parallel one which could also achieve around 76.1% top1 on Kinetics-400. The weight of r50f8s8 is available at our shared google drive while those of other settings would be available in future. Thanks again.
